### ISSUE TITLE
How to save and get collection having nested collections?

### ISSUE THREAD

**Issue by ghost** [SwiftORM/MongoDB-StORM#13]
I'm using Perfect Server Side Swift

Error while calling save() method of A:

error("notConvertible(Optional(ProjectName.B))")

I'm getting error while saving the below collection having nested collections

{
 "name": "a1",
  "b" :  {
    "name": "b2"
   "c": {
"name": "c2"
  }
  },
"e": {
"name": "e1"
}
}

Please help I don't know where examples are there? Difficult to find! MongoDB-Strom examples are rare in internet.

**Class A:**

import Foundation
import MongoDBStORM
import StORM

open class A : MongoDBStORM {
    var id: String = ""
    var name: String = ""
    var b: B = B()
}

**Class B:**

import Foundation
import MongoDBStORM
import StORM

open class B : MongoDBStORM {
    var id: String = ""
    var name: String = ""
   var c:C = C()
}
...
....
Etc.,

Calling save() method within other class save() method works, if I used an id (string), as a reference for child. But it is not efficient. as below:

import Foundation
import MongoDBStORM
import StORM

/// Provides the Account structure for Perfect Turnstile
open class A : MongoDBStORM {
    var id: String = ""
    var name: String = ""
    var bId: String = ""
    
    /// The databse to store the data
    override init() {
        super.init()
        _collection = "A"
    }
    
    /// Set incoming data from database to object
    override open func to(_ this: StORMRow) {
        id    = this.data["_id"] as? String ?? ""
        name    = this.data["name"] as? String ?? ""
        bId   = this.data["bId"] as? String ?? ""
    }
    
    /// Iterate through rows and set to object data
    public func rows() -> [A] {
        var rows = [A]()
        for i in 0..<self.results.rows.count {
            let row = A()
            row.to(self.results.rows[i])
            rows.append(row)
        }
        return rows
    }

    
    /// Triggers creating a new token.
    public func new(b: B) -> String {
        do {
           b.id = b.newObjectId();
            try b.save()
            a.bId = b.id
            try save()
        } catch {
            print(error)
        }
        return id
    }
    
}

**Comment by iamjono** [comment]
So you're saying that b and C are collections - if B and C are being stored in their own collection than you should be using their ID's as the link instead of including the whole structure in the field.

```
open class A : MongoDBStORM {
var id: String = ""
var name: String = ""
var b: String = ""

var _b: B: B()
}
```

This way the `_b` is not loaded, but the id for it is stored. Then on load (i.e. the `rows()` function then if `b` is not empty then load the related row using the id.

Does that make sense?

**Comment by ghost** [comment]
Yes that's how I tried, but is it efficient? Don't we leave it to Mongo DB to extract the child tables? If I do this way for each child table it goes to database server from app server

**Comment by iamjono** [comment]
The ORM is not going to know it's a nested collection otherwise. You could in theory use `Codable` structures as your nested data, but they won't be properly searchable in Mongo.

I suggest you use the linked id method in this case.

**Comment by ghost** [comment]
OK thanks a lot for replying. I go with linked id method and use Mongodb queries to link child tables.  I'm not sure I've disturbed your free time! Love you!

**Comment by iamjono** [comment]
No problem! Hope things go well with the project :)

If you need more timely help join the Perfect Slack channel, and tag me (@iamjono)
